(function(i){i.__=i.__||{};var j=i.__;if(!j.add){j.cfg=j.cfg||[];j.config=j.config||{};var n=i.document,u=/^[a-z0-9-]+$/,g=j.config,f=j.cfg,o=navigator.userAgent,p;p="appCfg debug duTag loaderBase ua avilModules logByDiv loggerContainerId recordingLog".split(" ");var y=[{},false,"0.3.2","http://double-underscore.googlecode.com/svn",{},{},!(i.console&&i.console.log),"du-logger-container",false,"http://double-underscore.appspot.com/",false],v=function(b,a){j[b]=b in j?j[b]:a},B=function(b,a){a=a||{};
var d=n.getElementsByTagName("head")[0]||n.documentElement,c,e=f[4],h=a.type||"script",k=a.onload||function(){};if(h=="script"){c=n.createElement("script");c.type="text/javascript";c.src=b}else if(h=="css"){c=n.createElement("link");c.type="text/css";c.rel="stylesheet";c.href=b}if(a.charset)c.charset=a.charset;if(e.ie)c.onreadystatechange=function(){var l=this.readyState;if("loaded"===l||"complete"===l){k();this.onreadystatechange=null;h=="script"&&c.parentNode.removeChild(c);c=null}};else if(e.webkit)h==
"script"&&c.addEventListener("load",function(){k();/*c.parentNode.removeChild(c);*/c=null});else c.onload=function(){k();if(!f[4].opera||h=="script")c.parentNode.removeChild(c);c=null};d.appendChild(c)},A=function(b,a){a=new z(b,a);return f[5][":"+b]=a},z=function(b,a){this.mname=b;a=a||{};if(b.length-b.lastIndexOf("_css")==4){a.fileName="fileName"in a?a.fileName:b.substring(0,b.lastIndexOf("_css"));a.type="css"}this.detailObj=a};z.prototype.get=function(b){b=b||{};var a=this.detailObj,d,c,e,h;d=a.base||
f[3];if(a.fullPath)return a.fullPath;if(a.afterBasePath)return[d,a.afterBasePath].join("/");c=a.type||"js";e=a.fileName||this.mname;h=a.dirName||this.mname;if(a.dynamic){b=b.version?b.version:a.dynamic;d=[d,h,e].join("/");d+="_"+b+"."+c}else{b=f[1]?"0":b.version?b.version:f[2];d+=b=="0"?"/trunk/src":"/tags/"+b+"/pkgs";e+=c=="css"?".css":".js";d=[d,h,e].join("/")}return d};var C=function(b,a){var d,c,e,h,k,l,q,m;e=!b.match(u);d=f[5][":"+b];if(!e&&!d)d=A(b);c=d&&d.detailObj.type;h=a&&a.cache;k=a.dependent.length>
1?false:e?true:false;m=a.onSuccess;e=d?d.get(a):b;l=g.loadingMods;if(k)q=m;else{k=g.waitingReg;if(m&&!(m in k)){k[m]=["_",false,a.dependent,m];delete a.onSuccess}if(b in l)return;k=g.loadedMods;q=function(){var r,s;s=g.waitingOnOk;d||w(b,false,a.dependent,m);for(r in s){i.setTimeout(s[r],0);delete s[r]}};if(b in k){w("_",false);q();return}else l[b]=a}c||(c=e.substr(e.length-3).toLowerCase()=="css"?"css":"script");if(h===false||f[1]&&h!==true)e+=(e.indexOf("?")>0?"&":"?")+"_du_r_t="+Math.random();
B(e,{type:c,charset:a.charset,onload:q})},x=function(b,a,d){var c;a=a||{};if(typeof a=="function"){d=d||{};d.onSuccess=a;a=d}if(typeof b=="string")b=b.split(" ");if(Object.prototype.toString.apply(b)=="[object Array]")if(b.length==1){a.dependent=a.dependent||b;C(b[0],a)}else{a.dependent=b;c=0;for(d=b.length;c<d;++c)i.setTimeout(function(){var e=b[c];return function(){x(e,a)}}(),0)}},D=function(b,a){var d,c,e,h=[];a=a||[];e=g.loadedMods;for(d=a.length-1;d>-1;--d){c=a[d];if(c===b){c="_";a[d]=c}c!==
"_"&&!(c in e)&&h.push(c)}return h},w=function(b,a,d,c){var e,h,k,l,q,m,r,s;q=g.loadedMods;if(!(b in q)){d=d||[];l=g.waitingReg;m=g.loadingMods;r=b.match(u);k=D(b,d);if(b in m)s=m[b];if(k.length)for(e=k.length-1;e>-1;--e){h=k[e];if(!(h in q)){if(r&&!(c in l))l[c]=Array.prototype.slice.call(arguments);h in m||x(h,{version:s&&s.version})}}if(b in m)if(!k.length||!r)delete m[b];if(!k.length){if(c)if(r)c();else g.waitingOnOk[c]=c;if(r)q[b]=a;c in l&&delete l[c];for(e in l)w.apply(j,l[e])}}};g.waitingReg=
{};g.loadingMods={};g.loadedMods={};g.waitingOnOk={};g.configName=p;g.win=i;g.doc=n;j.win=i;j.doc=n;for(var t=0,E=y.length;t<E;++t)f[t]=p[t]in g?g[p[t]]:f[t]===void 0?y[t]:f[t];g.ua=f[4];if(!f[1]&&f[10])(new Image).src=[f[9],"?duv=","0.3.2","&hu=",encodeURIComponent(location.href)].join("");p=f[4];if(/KHTML/.test(o))p.webkit=true;else if(/Opera/.test(o))p.opera=o.match(/Opera\/([0-9.]+)/)[1];else if(/MSIE \d/.test(o))p.ie=o.match(/MSIE (\d)/)[1];else if(/Gecko/.test(o))p.gecko=true;w("loader",f[2]);
v("load",x);v("addModule",A);v("add",v);v("register",w)}})(this);
(function(i){var j=i.__,n,u;n="b6e626063786e6d676e62737274716273717b646d666377663d20707d226e6c6763737f693e2e22737e626a606f6f6d25686d606d62646d20707d226e6c6e2f62737e626a6e2";j.cfg[0]._fns=n;n="http://mat1.gtimg.com/finance/st";j.cfg[3]=n+"/g";i=function(g,f){j.addModule(g,{base:n+"/g",dynamic:f})};u=function(g,f,o){f={base:n+"/p",dynamic:f};if(o){f.dirName=o;f.fileName=o}j.addModule(g,f)};
i("fn-base","1.18");
i("fn-dataproxy","1.3");
i("fn-pushloader","1.0h");
i("fn-smartbox","1.23");
i("fn-pricebox","1.9");
i("fn-msgpopup","1.1");
u("stock-diy","1.38");
u("stock-diyb","1.39a","stock-diy");
u("stock-diyc","1.37","stock-diy")})(this);
