(function(E){var o=E.__,z;if(E.__&&E.__.add){z=o.cfg[2];o.register("lang",z,[],function(){var n=o.win,t=o.doc,p=o.cfg,l=Object.prototype,r=function(){},b={"+":function(a,c){return a+c},"-":function(a,c){return a-c},"*":function(a,c){return a*c},"/":function(a,c){return a/c},"%":function(a,c){return a%c},"-2":function(a,c){return c-a},"/2":function(a,c){return c/a},"%2":function(a,c){return c%a},">":function(a,c){return a>c},"<":function(a,c){return a<c},">=":function(a,c){return a>=c},"<=":function(a,
c){return a<=c},"==":function(a,c){return a==c},"===":function(a,c){return a===c},"&&":function(a,c){return a&&c},"||":function(a,c){return a||c},"&":function(a,c){return a&c},"|":function(a,c){return a|c},"^":function(a,c){return a^c},"++":function(a){return a+1},"--":function(a){return a-1},"!":function(a){return!a}},e={ELEMENT_NODE:1,ATTRIBUTE_NODE:2,TEXT_NODE:3,CDATA_SECTION_NODE:4,ENTITY_REFERENCE_NODE:5,ENTITY_NODE:6,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,
DOCUMENT_FRAGMENT_NODE:11,NOTATION_NODE:12},j=function(a){return typeof a==="function"},k=function(a){return a&&(typeof a==="object"||j(a))||false},q=function(a){return typeof a==="string"},d=function(a,c,g,h){var B;h=h===true?true:false;if(a)if(g)for(B in a){if(h||a.hasOwnProperty(B))c(a[B],B)}else{if(typeof a=="string"||typeof a.length!=="number"||a.tagName||a===n)a=[a];B=0;for(g=a.length;B<g;++B)c(a[B],B)}},f=function(a,c,g){g=g||1;var h=[];if(c===void 0){c=a;a=0}for(;c>a;){h[h.length]=a;a+=g}return h},
u=function(a,c,g,h){d(a,function(B,A){g=c(g,B,A)},h);return g},m=function(a){if(!a)return[];for(var c=a.length||0,g=new Array(c);c--;)g[c]=a[c];return g},s=function(a,c,g){var h=false;d(c,function(B,A){if(B===a||!g&&B==a){h=h===false?(h=[]):h;h[h.length]=A}});return h},w=function(a){if(a===null||typeof a!="object")return a;var c=new a.constructor;for(var g in a)if(a.hasOwnProperty(g))c[g]=w(a[g]);return c},y=function(a,c,g){g=g===false?false:true;for(var h in c)if(g||!(h in a))a[h]=c[h]},i=function(a){a=
a.replace(x("^\\s\\s*"),"");for(var c=x("\\s"),g=a.length;c.test(a.charAt(--g)););return a.slice(0,g+1)},v=function(a,c){return a.indexOf(c)===0},x=function(){var a={};return function(c,g){var h=c+(g||"");a[h]||(a[h]=new RegExp(c,g));return a[h]}}(),C=function(){var a=0,c=0;return n.console?function(){if(p[1]!=false){var g=(new Date).getTime(),h,B=n.console;h=a||g;a=g;g=++c+",("+g+",+"+(g-h)+"ms): ";h=Array.prototype.slice.apply(arguments);h.unshift(g);B.log.apply?B.log.apply(B,h):B.log(h.join(" "))}}:
r}();y(o,{set:function(a,c){var g=a.split(".");a=n;for(var h=0,B=g.length-1;h<B;++h){a[g[h]]=a[g[h]]||{};a=a[g[h]]}g=g[g.length-1];a[g]=c===void 0?a[g]===void 0?{}:a[g]:c;return a[g]},get:function(a){a=a.split(".");for(var c=n,g=0,h=a.length;g<h;++g){if(!c)return;c=c[a[g]]}return c},isSet:function(a){return o.get(a)===void 0?false:true},toCall:function(a,c,g){g=g||1E3;var h=typeof c=="function"?c:function(){var A=false;if(o.isSet(c))A=true;return A},B;if(h())a();else B=setInterval(function(){if(h()){clearInterval(B);
a()}},g)},debug:function(a){p[1]=a===false?false:true},topLayer:1,e:d,log:C});o.add("Lang",{EF:r,K:function(a){return a},NODE_TYPE:e,OPER:b,isArray:function(a){return l.toString.apply(a)==="[object Array]"},isUndefined:function(a){return typeof a===void 0},isNull:function(a){return a===null},isBoolean:function(a){return typeof a==="boolean"},isFunction:j,isNumber:function(a){return typeof a==="number"&&isFinite(a)},isInt:function(a){var c=parseInt(a,10);if(isNaN(c))return false;return a==c&&a.toString()==
c.toString()},isFloat:function(a){var c=parseFloat(a);if(isNaN(c))return false;return a==c&&x("\\.").test(a)},isObject:k,isString:q,isEmpty:function(a){return a===null||typeof a==="undefined"||a===0||a===false||a===""||typeof a.length==="number"&&a.length===0},isNode:function(a,c){return k(a)&&(!c&&(a==n||a==t)||a.nodeType==e.ELEMENT_NODE)},each:d,e:d,range:f,all:function(a,c,g){var h;if(a){if(g)for(h in a){if(a.hasOwnProperty(h)&&!c(a[h],h))return false}else{if(typeof a=="string"||typeof a.length!==
"number"||a.tagName||a===n)a=[a];h=0;for(g=a.length;h<g;++h)if(!c(a[h],h))return false}return true}},find:function(a,c,g){var h;if(a){if(g)for(h in a){if(a.hasOwnProperty(h)&&c(a[h],h))return h}else{if(typeof a=="string"||typeof a.length!=="number"||a.tagName||a===n)a=[a];h=0;for(g=a.length;h<g;++h)if(c(a[h],h))return h}return-1}},any:function(a,c,g){var h;if(a){if(g)for(h in a){if(a.hasOwnProperty(h)&&c(a[h],h))return true}else{if(typeof a=="string"||typeof a.length!=="number"||a.tagName||a===n)a=
[a];h=0;for(g=a.length;h<g;++h)if(c(a[h],h))return true}return false}},reduce:u,map:function(a,c,g){var h=[];d(a,function(B,A){h[A]=c(B)},g);return h},a:m,w:function(a){if(!q(a))return[];return(a=i(a))?a.split(x("\\s+")):[]},unique:function(a,c){return u(a,function(g,h,B){if(0===B||(c?g[g.length-1]!=h:!s(h,g,true)))g.push(h);return g},[])},inArray:s,arrayRemove:function(a,c,g){var h=a.length;c=c<0?c-0+h:c;g=g<0?g-0+h:g;if(g<c||c>=h||g>=h)return false;g=a.slice((g||c)+1||a.length);a.length=c<0?a.length+
c:c;return a.push.apply(a,g)},absorb:function(a,c){var g=[];d(a,function(h){g.push(h[c])});return g},curry:function(a){a=typeof a=="string"&&b[a]?b[a]:a;var c=m(arguments);c.shift();return function(){return a.apply(null,c.concat(m(arguments)))}},compose:function(a,c){return function(){return a(c.apply(null,arguments))}},negate:function(a){return function(){return!a.apply(null,arguments)}},keys:function(a){var c=[];d(a,function(g,h){c.push(h)},true);return c},values:function(a){var c=[];d(a,function(g){c.push(g)},
true);return c},clone:w,objExtend:y,getMergedObj:function(a,c){var g={},h;for(h in a)if(a.hasOwnProperty(h))g[h]=a[h];if(c)for(h in c)if(c.hasOwnProperty(h))g[h]=c[h];return g},trim:i,truncate:function(a,c,g,h){var B=a.length,A,F=0;c=c||30;g=g===void 0?"...":g;if((h=h===void 0?false:true)&&B>c/2){h=0;for(A=g.length;h<A;h++)F+=g.charCodeAt(h)>255?2:1;for(h=0;h<B;h++){F+=a.charCodeAt(h)>255?2:1;if(F>c)break}a=a.substring(0,h)+g}else if(a.length>c)a=a.slice(0,c-g.length)+g;else a+="";return a},strRepeat:function(a,
c){var g=[];d(f(c),function(){g[g.length]=a});return g.join("")},baseConvert:function(a,c,g){if(!a||!c)return false;a=String(a).toLowerCase();if(g===void 0)g=v(a,"0x")?16:v(a,"0")?8:10;a=parseInt(a,g);return a.toString(c)},stripTags:function(a){return a.replace(x("<\\/?[^>]+>","gi"),"")},camelize:function(a){var c=a.split("_"),g=c.length;if(g==1)return c[0];a=a.charAt(0)=="_"?c[0].charAt(0).toUpperCase()+c[0].substring(1):c[0];for(var h=1;h<g;++h)a+=c[h].charAt(0).toUpperCase()+c[h].substring(1);
return a},underscore:function(a){return a.replace(x("([A-Z]+)([A-Z][a-z])","g"),"$1_$2").replace(x("([a-z\\d])([A-Z])","g"),"$1_$2").toLowerCase()},capitalize:function(a){return a.charAt(0).toUpperCase()+a.substring(1).toLowerCase()},sprintf:function(a){for(var c=1;arguments[c]!==void 0;)a=a.replace(x("%s"),arguments[c++]);return a},startWith:v,beginWith:v,endWith:function(a,c){var g=a.length-c.length;return g>=0&&a.lastIndexOf(c)===g},greplace:function(a,c,g){var h=x(c,"g"),B=x(c),A,F="";d(a.match(h),
function(D,H){A=a.indexOf(D)+D.length;F+=a.substring(0,A).replace(B,g(D,H));a=a.substring(A)});return F+a},rand:function(a,c){if(c===void 0){c=a;a=0}return Math.round(Math.random()*(c-a))+a},getReg:x});o.add("Log",C)});o.register("dom",z,["lang"],function(){var n=o.Lang,t=o.doc,p=o.cfg,l=t.documentElement,r=function(b){return typeof b=="string"?t.getElementById(b):b};o.add("Dom",{$:function(b){return(b=r(b))?[b]:[]},f:r,id:r,hasClass:function(b,e){return n.getReg("(?:^|\\s+)"+e+"(?:\\s+|$)").test(b.className)},
addClass:function(b,e){if(!o.Dom.hasClass(b,e))b.className=n.trim([b.className,e].join(" "))},remClass:function(b,e){var j=o.Dom;if(e&&j.hasClass(b,e)){b.className=n.trim(b.className.replace(n.getReg("(?:^|\\s+)"+e+"(?:\\s+|$)")," "));j.hasClass(b,e)&&j.remClass(b,e)}},getElementsByClassName:function(){return t.getElementsByClassName?function(b,e){return b.getElementsByClassName(e)}:function(b,e){var j=e.split(" ");e=[];b=b.all?b.all:b.getElementsByTagName("*");var k=[],q;q=0;for(var d=j.length;q<
d;q+=1)e.push(n.getReg("(^|\\s)"+j[q]+"(\\s|$)"));d=0;for(var f=b.length;d<f;d+=1){j=b[d];q=false;for(var u=0,m=e.length;u<m;u+=1){q=e[u].test(j.className);if(!q)break}q&&k.push(j)}return k}}(),insertBefore:function(b,e){e.parentNode&&e.parentNode.insertBefore&&e.parentNode.insertBefore(b,e)},insertAfter:function(b,e){e.nextSibling?e.parentNode.insertBefore(b,e.nextSibling):e.parentNode.appendChild(b)},addEl:function(b,e){if(!b)return false;var j,k,q,d,f=function(m){o.Dom.addClass(j,m)},u=function(m){o.Dom.addEl(m,
j)};if(n.isArray(b)){d=t.createDocumentFragment();n.e(b,function(m){o.Dom.addEl(m,d)});if(e=r(e))d=e.appendChild(d);return d}if("_t"in b){b.tag="_text";b.text=b._t}k=b.tag;if(!k&&e&&e.tagName)switch(e.tagName.toLowerCase()){case "table":case "tbody":k="tr";break;case "tr":k="td";break;case "ul":k="li";break;case "select":k="option";break}k=k||"div";if(o.cfg[4].ie&&(k=="input"||k=="select")&&"name"in b)j=t.createElement("<input name="+b.name+">");else if(k=="_text"){j=t.createTextNode(b.text);b={}}else j=
t.createElement(k);if(!j)return false;for(q in b)if(b.hasOwnProperty(q)){k=b[q];switch(q){case "cls":n.e(k,f);break;case "child":n.e(k,u);break;case "text":j.appendChild(t.createTextNode(k));break;case "css":j.style.cssText=k;break;case "html":j.innerHTML=k;break;default:j[q]=k;break}}if((e=o.Dom.f(e))&&e.appendChild)j=e.appendChild(j);return j},remEl:function(b){var e=function(k){k=o.Dom.$(k);n.e(k,function(q){q&&q.parentNode&&q.parentNode.removeChild(q)})};if(n.isArray(b))for(var j=b.length-1;j>
-1;j--)e(b[j]);else e(b)},addText:function(b,e){b.appendChild(t.createTextNode(e))},addStyle:function(b){if(t.createStyleSheet)t.createStyleSheet("").cssText=b;else this.addEl({tag:"style",textContent:b},t.getElementsByTagName("head")[0])},getScrollXY:function(){var b=Math.max(l.scrollTop,t.body.scrollTop);return[Math.max(l.scrollLeft,t.body.scrollLeft),b]},getPosition:function(b,e){for(var j=0;!n.isEmpty(b.offsetParent);){j+=b[e];b=b.offsetParent}j+=t.body[e]-0;return j},v:function(b){if(b=this.f(b))return b.value;
return false},getWindowXY:function(){var b=self.innerHeight,e=self.innerWidth,j=t.body,k=t.compatMode;if(k||p[4].ie)if(k=="CSS1Compat"){b=p[4].opera?b:l.clientHeight;e=l.clientWidth}else{b=p[4].opera?b:j.clientHeight;e=j.clientWidth}return[e,b]},getDocumentXY:function(){var b=t.body,e=t.compatMode!="CSS1Compat"||p[4].webkit?b.scrollWidth:l.scrollWidth;b=t.compatMode!="CSS1Compat"||p[4].webkit?b.scrollHeight:l.scrollHeight;var j=o.Dom.getWindowXY();e=Math.max(e,j[0]);b=Math.max(b,j[1]);return[e,b]},
setCenter:function(b){var e=this.getWindowXY(),j=this.getScrollXY(),k=b.offsetWidth||b.clientWidth||parseInt(b.style.width,10),q=b.offsetHeight||b.clientHeight||parseInt(b.style.height,10);b.style.position="absolute";b.style.left=(e[0]-k)/2+j[0]+"px";e=(e[1]-q)/2+j[1];b.style.top=(e<50?50:e)+"px"}})});o.register("selector",z,["lang","dom"],function(){o.add("Selector",function(){function n(d,f){var u,m,s,w,y,i,v;d=p.unique(d);if(f.tagname){u=[];m=p.getReg("\\b"+f.tagname+"\\b","i");s=0;for(w=d[r];s<
w;++s)m.test(d[s].tagName)&&u.push(d[s]);d=u}if(f.classname){u=[];m=f.classname[b](" ");f=[];s=0;for(w=m[r];s<w;++s)f.push(p.getReg("(^|\\s)"+m[s]+"(\\s|$)"));s=0;for(w=d[r];s<w;++s){v=d[s];i=e;m=0;for(y=f[r];m<y;m++){i=f[m].test(v.className);if(!i)break}i&&u.push(v)}d=u}return d}var t=o.Dom,p=o.Lang,l=o.doc,r="length",b="split",e=false,j=l.documentElement,k,q;t.$=function(d,f,u){var m;if(d)if(d.nodeType)m=[d];else if(d.item){m=[];f=0;for(u=d[r];f<u;++f)m[m[r]]=d[f]}else{if(typeof d==="string")m=
(m=f?null:t.id(d))?[m]:q(d,f,u)}else m=[];return m};t.f=function(){return t.$.apply(t,arguments)[0]};k=function(){if(j.contains)return function(d,f){if(!d||!f||!d.tagName||!f.tagName)return e;return f.contains(d)};else if(j.compareDocumentPosition)return function(d,f){if(!d||!f||!d.tagName||!f.tagName)return e;return!!(f.compareDocumentPosition(d)&16)}}();t.contains=k;q=function(){return l.querySelectorAll?function(d,f,u){var m=[];if(f&&!f.nodeName){f=t.f(f);if(!f)return m}f=f||l;if(u)m[0]=f.querySelector(d);
else{u=f.querySelectorAll(d);d=0;for(f=u[r];d<f;++d)m.push(u[d])}return m}:function(d,f,u){var m=[],s,w,y,i,v,x,C,a,c,g;if(!d)return m;d=p.trim(d);s=p.trim(d)[b](",");if(s[r]>1){d=0;for(y=s[r];d<y;++d){w=q(s[d],f,u);if(u&&w[r]>1){m[0]=w[0];break}else m=m.concat(w)}return m}if(f&&!f.nodeName){f=t.f(f);if(!f)return m}f=f||l;f=[f];u=d[b](" ");C=e;s=0;for(w=u[r];s<w;s++){d=u[s];if(d==">")C=true;else{m=[];i=d.match(p.getReg("^([^.#]+)"));v=d.match(p.getReg("#([^.#]+)"));x=(d=d.match(p.getReg("\\.[^.#]+",
"g")))?d.join(" ").replace(p.getReg("\\.","g"),""):"";if(v){m=(m=t.id(v[1]))?[m]:[];i=i?i[1]:null}else if(i||d){d=0;for(y=f[r];d<y;++d){a=i?f[d].getElementsByTagName(i[1]):t.getElementsByClassName(f[d],x);if(C){c=0;for(g=a[r];c<g;c++)a[c].parentNode===f[d]&&m.push(a[c])}else m=m.concat(p.a(a))}x=i?x:null;i=null}m=n(m,{tagname:i,classname:x});if(v&&m[0]){v=e;d=0;for(y=f[r];d<y;++d){i=f[d];if(C?m[0].parentNode===i:i==l||k(m[0],i)){v=true;break}}v||(m=[])}C=e;f=m;if(f[r]===0)break}}return f}}();return{query:q}}())});
o.register("event",z,["lang","dom"],function(){o.add("Event",function(){var n=o.Lang,t=o.Dom,p=o.win,l=o.doc,r=o.cfg,b={},e=function(){return p.addEventListener?function(i,v,x,C){var a,c;i=typeof i=="string"?t.$(i):i;if(v.indexOf(":")>-1){c="dataavailable";a=function(g){g.eventName===v&&x(g)}}else{c=v;a=x}b[x]=a;n.e(i,function(g){o.Event.listeners++;g.addEventListener(c,a,!!C)})}:p.attachEvent?function(i,v,x){var C,a;i=typeof i=="string"?t.$(i):i;if(v.indexOf(":")>-1){a="dataavailable";C=function(c){c=
c||p.event;c.target=c.target||c.srcElement;c.eventName==v&&x(c)}}else{a=v;C=function(c){c=c||p.event;c.target=c.target||c.srcElement;x(c)}}b[x]=C;n.e(i,function(c){o.Event.listeners++;c.attachEvent("on"+a,C)})}:function(){}}(),j=function(){return p.removeEventListener?function(i,v,x,C){var a;i=typeof i=="string"?t.$(i):i;v=v&&v.indexOf(":")>-1?"dataavailable":v;a=b[x];delete b[x];n.e(i,function(c){o.Event.listeners--;c.removeEventListener(v,a,!!C)})}:p.detachEvent?function(i,v,x){var C;i=typeof i==
"string"?t.$(i):i;v=v&&v.indexOf(":")>-1?"dataavailable":v;C=b[x];delete b[x];n.e(i,function(a){o.Event.listeners--;a.detachEvent("on"+v,C)})}:function(){}}(),k=function(i){if(i.stopPropagation)i.stopPropagation();else i.cancelBubble=true},q=function(i){if(i.preventDefault)i.preventDefault();else i.returnValue=false},d=[],f=false,u=false,m,s=function(){var i;if(!u){u=true;"readyState"in l&&l.readyState=="complete"&&w();if(r[4].ie)m=setInterval(function(){try{l.documentElement.doScroll("left");clearInterval(m);
m=null;w()}catch(v){}},50);else l.addEventListener("DOMContentLoaded",w,false);i=p.onload;p.onload=typeof i!="function"?w:function(){w();i()}}},w=function(){if(!f){f=true;n.e(d,function(i){i()});d=null}},y=function(i){s();f?i.call(p):d.push(function(){return i.call(p)})};o.on=e;o.onReady=y;return{listeners:0,on:e,off:j,fire:function(i,v,x){i=t.f(i)||l;if(i==l&&l.createEvent&&!i.dispatchEvent)i=l.documentElement;var C;if(l.createEvent){C=l.createEvent("HTMLEvents");C.initEvent("dataavailable",true,
true)}else{C=l.createEventObject();C.eventType="ondataavailable"}C.eventName=v;C.memo=x||{};l.createEvent?i.dispatchEvent(C):i.fireEvent(C.eventType,C);return C},stopEvent:function(i){q(i);k(i)},stopPropagation:k,preventDefault:q,onReady:y,bind:function(i,v){return function(){i.apply(v,n.a(arguments))}}}}())});o.register("io",z,["lang"],function(){E.JSON||o.load("json");o.add("Io",function(){var n=o.Lang,t=o.cfg,p=o.log,l=function(){var b=0,e=function(){var j,k,q,d=[function(){return new XMLHttpRequest},
function(){return new ActiveXObject("Microsoft.XMLHTTP")},function(){return new ActiveXObject("Msxml2.XMLHTTP")}];j=0;for(k=d.length;j<k;++j)try{if(q=d[j]()){e=d[j];return q}}catch(f){}};return function(j,k,q){var d,f,u;if(q===void 0)u="GET";else{u="POST";q=n.isString(q)||!JSON?q:JSON.stringify(q)}k.__du_ajax_id=b++;k.onSuccess="onSuccess"in k?k.onSuccess:function(m){o.log("Success!\nServer returns:"+m.responseText)};k.onFailure="onFailure"in k?k.onFailure:function(){o.log("xmlhttp request Failed!")};
k.timeout=k.timeout?k.timeout:6E4;d=e();f=function(){if(d.readyState==4&&d.status==200){k.onSuccess(d.responseText,d);d=null}else if(d.readyState==4){k.onFailure(d);d=null}};d.onreadystatechange=f;d.open(u,j,true);d.setRequestHeader("Content-Type","application/x-www-form-urlencoded");d.send(q);f=null;k.xhr=d;return k}}(),r=function(){var b=function(s){var w=[];n.e(q,function(y){y[0].id!==s.id&&w.push(y)});q=w;u()},e=function(s){var w=s.detail;w.onSuccess=function(y,i){b(s);if(w.target&&o.Dom)o.Dom.f(w.target).innerHTML=
y;w.onOk&&w.onOk(y,i)};w.onFailure=function(y,i){p("xmlhttp request #"+s.id+" failed");b(s);if(w.target&&o.Dom)o.Dom.f(w.target).innerHTML="xmlhttp request #"+s.id+" failed";w.onFail&&w.onFail(y,i)};return l(f(w.sUrl,w.oGet,w.cache),w,w.sPost)},j=[],k=t[4].ie&&t[4].ie<8?2:4,q=[],d=0,f=function(s,w,y){if(w||!y){if(s.indexOf("?")<0)s+="?";y||(s+="&_durd="+Math.random());w&&n.e(w,function(i,v){s+=["&",encodeURIComponent(v),"=",encodeURIComponent(i)].join("")},true)}return encodeURI(s)},u=function(){if(!(q.length>=
k)){var s=j.shift();s&&q.push([s,e(s)])}},m=function(s,w){this.id=d++;s.cache=!!s.cache;this.detail=s;this.filter=w};return{push:function(s){var w=s.fnFilter,y,i=[];s.cache="cache"in s?s.cache:true;y=new m(s,w);if(w){n.e(j,function(v){w(v,s)&&i.push(v)});j=i;n.e(q,function(v){if(!w(v,s)){v[1].xhr.abort();b(v[0])}})}j.push(y);u()}}}();return{load:o.load,ajax:l,p:function(b,e,j){j=j||{};if(typeof e=="object")j=e;else if(n.isFunction(e))j.onOk=e;if(typeof b=="object")j=b;else if(n.isString(b))j.sUrl=
b;r.push(j)}}}())});o.register("cookie",z,[],function(){o.add("Cookie",function(){var n=o.doc,t=function(p){var l=n.cookie,r=p+"=",b=l.indexOf("; "+r),e;if(b==-1){b=l.indexOf(r);if(b!==0)return""}else b+=2;p=l.indexOf(";",b);if(p==-1)p=l.length;l=l.substring(b+r.length,p);try{e=decodeURIComponent(l)}catch(j){e=l}return e};return{get:t,del:function(p,l,r){var b=p+"=";if(t(p)){if(l)b+="; path="+l;if(r)b+="; domain="+r;b+="; expires=Thu, 01-Jan-70 00:00:01 GMT";n.cookie=b}},set:function(p,l,r){r=r||
{};p=p+"="+encodeURIComponent(l);if(r.expires){l=r.expires;l.toGMTString||(l=new Date(l));p+="; expires="+l.toGMTString()}if(r.path)p+="; path="+r.path;if(r.domain)p+="; domain="+r.domain;if(r.secure)p+="; secure";n.cookie=p}}}())});o.register("class",z,["lang"],function(){o.add("Class",function(){var n=o.Lang,t=false,p=n.getReg("xyz").test(function(){})?n.getReg("\\b_super\\b"):n.getReg(".*");n=function(){};n.extend=function(l){function r(){!t&&this.init&&this.init.apply(this,arguments)}var b=this.prototype;
t=true;var e=new this;t=false;var j=function(q,d){return function(){var f=this._super;this._super=b[q];var u=d.apply(this,arguments);this._super=f;return u}};for(var k in l)if(l.hasOwnProperty(k))e[k]=typeof l[k]=="function"&&typeof b[k]=="function"&&p.test(l[k])?j(k,l[k]):l[k];r.prototype=e;r.constructor=r;r.extend=arguments.callee;return r};return n}())});o.register("drag",z,["lang","dom","event"],function(){o.add("Drag",function(){var n=o.Dom,t=o.Event,p=o.Lang,l=o.doc,r=o.win,b,e=function(){if(b){t.off(l,
"mousemove",b[0]);t.off(l,"mouseup",b[1]);b=null}},j=function(d){var f;if("opacity"in d.style){f=d.style.opacity;f=f===""?"1":f}else{f=100;try{f=d.filters["DXImageTransform.Microsoft.Alpha"].opacity}catch(u){try{f=d.filters("alpha").opacity}catch(m){}}f/=100}return f},k=function(d,f){if("opacity"in d.style)d.style.opacity=f;if(p.isString(d.style.filter)){d.style.filter="alpha(opacity="+(f*100).toFixed(0)+")";if(!d.currentStyle||!d.currentStyle.hasLayout)d.style.zoom=1}},q=function(d,f,u,m,s,w,y){var i=
f.style,v=t.on;u=u===false?false:true;y=y||{};e();f.oriZ=p.isEmpty(i.zIndex)?1:i.zIndex;f.style.zIndex=++o.topLayer;if(!f.moved){f.moved=true;if(i.position.toLowerCase().indexOf("absolute")==-1)i.position="relative";if(i.left)f.oriL=parseInt(i.left,10);else{f.oriL=0;i.left="0px"}if(i.top)f.oriT=parseInt(i.top,10);else{f.oriT=0;i.top="0px"}if(m)f.zone={top:f.oriT-m.t,right:f.oriL+m.r,bottom:f.oriT+m.b,left:f.oriL-m.l}}m=parseInt(i.left,10);var x=parseInt(i.top,10),C=u?j(f):0,a=d.clientX-m,c=d.clientY-
x,g=n.getWindowXY();m=function(){e();u&&k(f,C);f.style.zIndex=f.oriZ;o.topLayer--;B(!!d.preventDefault);s&&s(parseInt(i.left,10),parseInt(i.top,10),f.zone)};x=function(A){var F,D,H,G;F=A.clientX-a;A=A.clientY-c;if(f.zone){D=f.zone;F=D.left>F?D.left:F;F=D.right<F?D.right:F;A=D.top>A?D.top:A;A=D.bottom<A?D.bottom:A}if(y.autoScroll){D=n.getScrollXY();H=y.autoScroll;if("height"in H){G=H.height;if(A-D[1]-g[1]+G>H.bottomBorder){A+=G;D[1]+=G;r.scrollTo(D[0],D[1]);c-=G}else if(A-D[1]<H.topBorder){A-=G;D[1]-=
G;r.scrollTo(D[0],D[1]);c+=G}}if("width"in H){G=H.width;if(F-D[0]-g[0]+G>H.rightBorder){F+=G;D[0]+=G;r.scrollTo(D[0],D[1]);a-=G}else if(A-D[1]<H.topBorder){A-=G;D[0]-=G;r.scrollTo(D[0],D[1]);a+=G}}}i.left=F+"px";i.top=A+"px";w&&w(F,A,f.zone);return false};var h,B=function(A){if(A)l.onmousedown=h;else l.onselectstart=h};(function(A){if(A){h=l.onmousedown;l.onmousedown=function(F){F.preventDefault()}}else{h=l.onselectstart;l.onselectstart=function(){return false}}})(!!d.preventDefault);if(u)k(f,y.opacity||
0.7);v(l,"mousemove",x);v(l,"mouseup",m);b=[x,m]};return{purge:e,bind:function(d,f,u,m,s,w){d=n.f(d);t.on(d,"mousedown",function(y){q(y,d,f,u,m,s,w)})},unbind:function(){},handler:q}}())});o.register("core",z)}})(this);
(function(E){var o=E.__;E.__&&E.__.add&&o.register("anim",o.cfg[2],["core"],function(){o.Anim||function(){o.log("Anim: Def begin.");o.add("Anim",function(){var z=function(n,t,p){var l=this;if(typeof p!="object")p={to:p};this.el=typeof n=="string"?o.Dom.f(n):n;this.attr=t;this.from="from"in p?p.from:false;this.to=p.to;this.unit="unit"in p?p.unit:"";this.lasttime="lasttime"in p?p.lasttime:300;this.interval="interval"in p?p.interval:15;this.max="max"in p?p.max:this.lasttime*2/this.interval;this.onOver=
"onOver"in p?p.onOver:o.Lang.EF;this.paused=false;this.iid=null;this.running=false;this._set=function(){var r=p.isStyle===false?l.el:l.el.style;return t=="opacity"&&typeof r.filter=="string"?function(b){r.filter="alpha(opacity="+b*100+")"}:function(b){r[t]=b+l.unit}}();this._get=function(){var r=p.isStyle===false?l.el:l.el.style;return t=="opacity"&&typeof r.filter=="string"?function(){var b=100;try{b=l.el.filters["DXImageTransform.Microsoft.Alpha"].opacity}catch(e){try{b=l.el.filters("alpha").opacity}catch(j){}}return b/
100}:function(){return parseFloat(r[t])||0}}()};z.prototype={run:function(){if(!this.running){this.running=true;var n;if(!this.paused){n=this.from;this.from=n===false?this._get():n;this.piece=(this.to-this.from)*(this.interval+1)/this.lasttime;this._set(this.from+this.piece);this.from=n}if(this.piece===0){this.running=false;this.onOver&&this.onOver()}else this.iid=this._begin()}},_begin:function(){var n=this,t=function(){return n.piece>0?function(){var p=n._get();if(n.count++>=n.max||p+n.piece>=n.to){n._stop();
n._set(n.to);n.onOver&&n.onOver()}else n._set(p+n.piece)}:function(){var p=n._get();if(n.count++>=n.max||p+n.piece<=n.to){n._set(n.to);n._stop();n.onOver&&n.onOver()}else n._set(p+n.piece)}}();this.count=0;return setInterval(t,n.interval)},pause:function(){this.paused=true;this.running=false;clearInterval(this.iid)},_stop:function(){this.running=false;clearInterval(this.iid)},stop:function(){this.running&&this._stop()}};return z}());__.log("Anim: Def end.")}()})})(this);
__.register("fn-table","1.4",["lang","dom"],function(){typeof __!="undefined"&&!__.Table&&function(){__.log("Table: Def begin.");var E=__,o=E.Dom,z=E.Lang,n=E.config.win,t,p,l=E.cfg;E.add("Table",{MAP_STOCKTYPE:{0:"jj",1:"sh",51:"sz",100:"hk",200:"us"},_findNextEl:function(b){for(;;){b=b.nextSibling;if(!b||b.nodeType===1)break}return b},_getUrlByType:function(b,e){var j="";b+="";e+="";switch(e){case "":case "0":if(b.length>5)j="http://stockhtm.finance.qq.com/fund/djj_jjcx/"+b+".htm";break;case "1":if(b.substr(0,
3)=="000")j="http://stockhtm.finance.qq.com/hqing/zhishu/"+b+".htm";break;case "51":if(b.substr(0,2)=="39")j="http://stockhtm.finance.qq.com/hqing/zhishu/"+b+".htm";break;case "100":if(b.length<=5)j="http://stockhtm.finance.qq.com/hk/ggcx/"+b+".htm";break;case "200":if(b.substr(0,1)==".")b=b.substr(1);j="http://stockhtm.finance.qq.com/astock/ggcx/"+b.toUpperCase()+".htm";break;case "300":j="http://stockhtm.finance.qq.com/if/ggcx/"+b.toUpperCase()+".shtml";break;case "350":j="http://stockhtm.finance.qq.com/money/future/quotpage/f/"+
b.toUpperCase()+".htm";break}return j||"http://stockhtm.finance.qq.com/sstock/ggcx/"+b+".shtml"},fill:function(b,e,j,k){var q,d,f,u,m,s,w,y,i;k=k||{};s="cloneTr"in k?k.cloneTr:true;w="lineCount"in k?k.lineCount:Infinity;e=o.f(e);if(s){y=e.cloneNode(true);y.id=""}d=e;if(typeof b=="string"){i=[];z.e(b.split(","),function(v){i.push(n["v_"+v]||"")});b=i}e=0;for(q=b.length;e<q&&e<w;e++){if(b[e]===""||b[e]===null||b[e]===void 0)if(k.showError)b[e]="";else continue;b[e]+="";if(!d)if(s){d=y.cloneNode(true);
f.parentNode.insertBefore(d,f.nextSibling)}else break;f=d;if(e%2===0&&k.evenTr)d.style.cssText=k.evenTr;else if(e%2===1&&k.oddTr)d.style.cssText=k.oddTr;u=b[e].split("~");m=f.firstChild;m=m.nodeType===1?m:t._findNextEl(m);for(d=0;m;){m.innerHTML=t.process(j[d],u,d,m,e);m=t._findNextEl(m);d++}d=t._findNextEl(f)}},process:function(b,e,j,k,q){var d;if(e.length===1){d="--";if(typeof b=="function")try{d=b(e,j,k,q)}catch(f){}else if(typeof b=="string"&&typeof t.processors[b]!="function")d=b}else{d=typeof b==
"function"?b(e,j,k,q):typeof t.processors[b]=="function"?t.processors[b](e,j,k):b in e?e[b]:typeof b=="string"?b:e[j];if(d===""||d===void 0||d===null)d="--"}return d},processors:{R_PRICE:function(b,e){return p.GET_COLOR(b[3],b[2],e)},S_PRICE:function(b,e){return p.GET_COLOR(b[3],b[4],e)},L_PRICE:function(b,e){return p.GET_COLOR(b[3],b[32],e)},L_CHANGE:function(b){return p.GET_SIGNED_COLOR(b[31],b[31])},S_PERCENT:function(b){return p.GET_PERCENT(b[5])},L_PERCENT:function(b){return p.GET_PERCENT(b[32])},
TITLE:function(b){return p.GET_TITLE(b[2],b[0],b[1],false,"_blank")},GET_COLOR:function(b,e,j){return e>0?'<span style="color:#fe0002">'+b+"</span>":e<0?'<span style="color:#009900">'+b+"</span>":j?'<span style="color:#000">'+b+"</span>":b},GET_SIGNED_COLOR:function(b,e,j){return p.GET_COLOR((e>0?"+":"")+b,e,j)},GET_PERCENT:function(b,e){return z.isNumber(b-0)&&b!==""&&b!=="-"?p.GET_COLOR((b>0?"+":"")+b+"%",b,e):"-"},GET_TITLE:function(b,e,j,k,q){j=j.replace(z.getReg("[\\s\u3000]*","ig"),"");k=k?
Math.ceil(k/2)*2:8;q=q||"";var d=k/2,f;f=j;if(j.length>d){for(f=0;f<k;f++)j.charCodeAt(f)>255&&k>d&&k--;f=j.substring(0,k)}return'<a href="'+t._getUrlByType(b,e)+'" title="'+j+"("+b+')"'+(q?' target="'+q+'"':"")+">"+f+"</a>"}},sort:function(b,e,j,k){var q=o.f(b),d=o.$("tr",q),f=[],u=z.getReg("^\\s+$"),m={},s,w=null,y=function(i){i=i.cloneNode(true);var v=[];if(i&&i.nodeType===z.NODE_TYPE.TEXT_NODE)u.test(i.nodeValue)||v.push(i.nodeValue);else i&&i.nodeType===z.NODE_TYPE.ELEMENT_NODE&&i.hasChildNodes()&&
z.e(i.childNodes,function(x){v.push(y(x))});return v.join("")};j=j===false?false:true;z.e(d,function(i,v){var x;if(k)f[v]=k[v];else{x=y(i.childNodes[e]).replace("%","");x=parseFloat(x);f[v]=isNaN(x)?0:x}if(m[f[v]])m[f[v]].push(v);else m[f[v]]=[v];o.addClass(i,"du-table-sort-"+v)});z.e(f.sort(j?z.OPER["-"]:z.OPER["-2"]),function(i){try{var v="du-table-sort-"+m[i].pop();s=o.f("."+v,q);w?o.insertAfter(s,w):o.insertBefore(s,d[0].parentNode.firstChild);o.remClass(s,v);w=s}catch(x){E.log(x)}})},load:function(b,
e){var j="http://qt.gtimg.cn/r="+Math.random()+"q=";b=z.isArray(b)?b.join(","):b;E.load(j+b,e,{charset:"gbk",cache:true})},pFill:function(b,e,j){var k,q;typeof b=="string"&&z.e(b.split(","),function(d){if(n["v_"+d])if(typeof b=="string")b=[n["v_"+d]];else b.push(n["v_"+d])});z.e(b,function(d,f){d=d.split("~");z.e(j,function(u,m){if(k=o.f([e,f,m].join("-"))){try{q=t.process(u,d,m,k)}catch(s){q="--"}k.innerHTML=q}})})},getFloatByLength:function(b,e){var j,k,q=b-0;b+="";j=b.length;k=(b+"").indexOf(".");
return j<=e?b:k<=0||k>=e?q.toFixed(0):q.toFixed(e-k-1)}});t=E.Table;p=t.processors;l=l[0]._fns;var r=function(b){r=n.JSON?function(e){return n.JSON.parse(e)}:function(e){return n.eval(e)};return r(b)};l=(l+"").split("");E.log("Table: Def end.")}()});
(function(E){var o=E.__;o.register("fn-cronloader","1.2",["fn-table"],function(){if(!("CronLoader"in o)){var z=o.Lang,n=o.Table,t=o.log,p=E.console?function(l){E.console.log(l)}:z.EF;o.add("CronLoader",o.Class.extend({version:"1.2",_run:function(l){var r=this,b=[],e,j=true,k=this.count,q="",d=[],f=function(){if(b.length>0){e=b.splice(60,b.length);q=b.join(",");b=e;n.load(q,f)}else z.e(d,function(u){try{if(u&&u.onOk){u.onOk(k);u.runOnce&&r.unsubscribe(u.id)}}catch(m){t("cron job "+u.id+" failed:");
p(m)}})};l?z.e(this.jobs[l.split("-")[1]],function(u){var m;if(u.id===l){m=u.judge(0);if(u&&(m&1)===1&&u.qtName){j=false;q=u.qtName}(m&2)===2&&d.push(u)}}):z.e(this.jobs,function(u,m){k%m===0&&z.e(u,function(s){var w;w=s.judge(k);if(s&&(w&1)===1&&s.qtName){j=false;q+=q===""?s.qtName:","+s.qtName}(w&2)===2&&d.push(s)})},true);if(!j||d.length>0)if(q==="")f();else{b=z.unique(q.split(","));e=b.splice(60,b.length);q=b.join(",");b=e;n.load(q,f)}},subscribe:function(l){var r=l&&l.judge,b=-1,e,j=this;if(!("interval"in
l))l.interval=1;if(!("judge"in l)){r=l.interval;l.judge=r}if(r&&z.isInt(l.judge)&&r>0)l.judge=function(k){if(k%r===0)return 3;return 0};e=l.interval;if(z.isFunction(l.judge)&&z.isFunction(l.onOk)){b=this.idcount++;l.id=b+"-"+e;this.jobs[e]||(this.jobs[e]=[]);this.jobs[e].push(l)}l.noWait&&E.setTimeout(function(){j._run(l.id)},0);return l.id},unsubscribe:function(l){var r,b;r=(r=(r=l.split("-"))&&r[1])||1;b=z.find(this.jobs[r],function(e){if(e&&e.id===l)return true});if(b>-1){z.arrayRemove(this.jobs[r],
b);return true}return false},start:function(){if(this.count===-1){this.count++;this._run()}this.resume()},pause:function(){if(this._id!==null){E.clearInterval(this._id);this._id=null}},resume:function(){var l=this;if(this._id===null)this._id=E.setInterval(function(){l.count++;l._run()},1E3)},stop:function(){this.pause();this.jobs={};this.count=-1;this.idcount=0;this._id=null},init:function(){this.stop()}}))}})})(this);__.register("fn-base","1.18");
/*  |xGv00|eae323f8f61e05db8d53b0d3ea93a1a4 */