var miniNavConf = [
    {name: '腾讯大渝网', link: 'http://cq.qq.com/',boss: 'cqqqcom'},
    {name: '要闻', link: 'http://cq.qq.com/news/',boss: 'cqnews'},
    {name: '娱乐', link: 'http://cq.qq.com/ent/',boss: 'cqent'},
    {name: '社区', link: 'https://panda.qq.com/cq/',boss: 'cqbbs'},
	{name: '生活汇', link: 'https://www.qqmylife.com/',boss: 'cqqqlife'},
    {name: '视频', link: 'http://cq.qq.com/vod/',boss: 'cqvideo'},
    {name: '城市', link: 'http://cq.qq.com/city/',boss: 'cqcity'},
    {name: '房产', link: 'http://cq.house.qq.com/',boss: 'cqhouse'},
    {name: '家居', link: 'http://cq.qq.com/home/',boss: 'cqjiaju'},
    {name: '二手房', link: 'http://esf.db.house.qq.com/cq/',boss: 'cqesf'},
    {name: '汽车', link: 'http://chongqing.auto.qq.com/',boss: 'cqcar'},
	{name: '二手车', link: 'http://www.boyue99.cn/',boss: 'cqesc'},
    {name: '财经', link: 'http://cq.qq.com/dycj/',boss: 'cqcj'},
    {name: '美食', link: 'http://cq.qq.com/eat/',boss: 'cqeat'},
    {name: '食品', link: 'http://cq.qq.com/food/',boss: 'cqfood'},
    {name: '购物', link: 'http://cq.qq.com/shop/',boss: 'cqshop'},
    {name: '3C', link: 'http://cq.qq.com/3c/',boss: 'cq3c'},
	{name: '旅游', link: 'http://cq.qq.com/tour/',boss: 'cqtour'},
	{name: '健康', link: 'http://cq.qq.com/health/',boss: 'cqhealth'},
	{name: '亲子', link: 'http://cq.qq.com/ert/',boss: 'cqert'},
	{name: '教育', link: 'http://cq.qq.com/edu/',boss: 'cqdeu'},
	{name: '招聘', link: 'http://cq.qq.com/job/',boss: 'cqjob'},
	{name: '慈善', link: 'http://cq.qq.com/cqcs/',boss: 'cqcs'},
    {name: '更多城市', link: null, subnav: [
        {name: '永川', link: 'http://cq.qq.com/dyyc/',boss: 'cqyc'},
        {name: '万州', link: 'http://cq.qq.com/dywz/',boss: 'cqwz'},
        {name: '开州', link: 'http://cq.qq.com/dykz/',boss: 'cqkz'},
        {name: '垫江', link: 'http://cq.qq.com/dydj/',boss: 'cqdj'}
    ]}
];/*  |xGv00|aa867f2972b468c2d211fc491ffa31ae */