var miniNavConf = [
    {name: '首页', link: 'http://hn.qq.com/', boss: 'miniMav'},
    {name: '城市', link: 'http://hn.qq.com/city/', boss: 'miniMav'},
    {name: '旅游', link: 'http://hn.qq.com/travel/', boss: 'miniMav'},
    {name: '图片', link: 'http://hn.qq.com/photo/', boss: 'miniMav'},
    {name: '娱乐', link: 'http://hn.qq.com/ent/', boss: 'miniMav'},
    {name: '长沙客', link: 'http://hn.qq.com/talk/', boss: 'miniMav'},
    {name: '房产', link: 'http://cs.house.qq.com/', boss: 'miniMav'},
    {name: '家居', link: 'http://hn.qq.com/home/', boss: 'miniMav'},
    {name: '健康', link: 'http://hn.qq.com/health/', boss: 'miniMav'},
    {name: '财经', link: 'http://hn.qq.com/finance/', boss: 'miniMav'},
    {name: '汽车', link: 'http://changsha.auto.qq.com/', boss: 'miniMav'},
    {name: '乐活', link: 'http://hn.qq.com/lohas/', boss: 'miniMav'},
    {name: '教育', link: 'http://hn.qq.com/edu/', boss: 'miniMav'},
    {name: '游戏', link: 'http://hn.qq.com/games/', boss: 'miniMav'},
    {name: '创业', link: 'http://hn.qq.com/chuangye/', boss: 'miniMav'},
    //{name: '株洲', link: 'http://hn.qq.com/zz/', boss: 'miniMav'},
    //{name: '湘潭', link: 'http://hn.qq.com/xt/', boss: 'miniMav'},
    //{name: '衡阳', link: 'http://hn.qq.com/hy/', boss: 'miniMav'},
    //{name: '邵阳', link: 'http://hn.qq.com/sy/', boss: 'miniMav'},
    //{name: '益阳', link: 'http://hn.qq.com/yy/', boss: 'miniMav'},
    //{name: '娄底', link: 'http://hn.qq.com/ld/', boss: 'miniMav'},
    //{name: '郴州', link: 'http://hn.qq.com/cz/', boss: 'miniMav'},
    //{name: '永州', link: 'http://hn.qq.com/yz/', boss: 'miniMav'},
    //{name: '怀化', link: 'http://hn.qq.com/hh/', boss: 'miniMav'},
    //{name: '岳阳', link: 'http://hn.qq.com/yueyang/', boss: 'miniMav'},
    //{name: '常德', link: 'http://hn.qq.com/cd/', boss: 'miniMav'},
];
/*  |xGv00|599b10f7814f00f098d10312fdd4163d */